name: stylecheck_unittest

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install pytest
        run: python -m pip install --upgrade pip pytest

      - name: Test with unittest
        working-directory: ./calculator
        run: python3 -m unittest unittest.py

  check-style:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install pycodestyle
        run: python -m pip install --upgrade pip pycodestyle

      - name: Check Style
        run: pycodestyle --first *.py
